services:
    mysql:
        container_name: mysql
        hostname: mysql
        image: mysql:8.4.0
        command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
        environment:
            MYSQL_ROOT_PASSWORD: password
            MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
        ports:
            - '3306:3306'
        extra_hosts:
            - "host.docker.internal:host-gateway"
        volumes:
            - ./data:/var/lib/mysql:delegated
            - ./mysql/mysql.conf.d/mysqld.cnf:/etc/mysql/mysql.conf.d/mysqld.cnf:ro
            - ./mysql/my.cnf:/etc/mysql/my.cnf:ro
        networks:
            - mysql-net

networks:
    mysql-net: